server:
  port: 7071
spring:
  application:
    name: oauth2social
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:xAv3O82qvnN1}
            client-secret: ${GITHUB_ClIENT_SECRET:xc2aed93979e60f253d029f0}
          google:
            client-id: ${GOOGLE_CLIENT_ID:xAv3O82qvnN1}
            client-secret: ${GOOGLE_CliENT_SECRET:xc2aed93979e60f253d029f0}
    user:
      name: ${SECURITY_USERNAME:hansi}
      password: ${SECURITY_PASSWORD:password}
logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
    com:
      jovisco: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread])
      %yellow(%logger{15}) - %msg%n}
